name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Check git status
              run: git status

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                  git add .
                  git commit -m "Commit changes before bumping version"
              if: success() # Выполнять только в случае успешного выполнения предыдущих шагов

            - name: Bump version
              id: bump_version
              run: |
                  npm version patch -m "Bump version to %s"
                  echo "::set-output name=new_version::$(node -p "require('./package.json').version")"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  branch: master

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.bump_version.outputs.new_version }}
                  release_name: Release ${{ steps.bump_version.outputs.new_version }}
                  body: |
                      Describe your changes here

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
