name: Release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Bump version
              id: bump_version
              run: |
                  npm version patch -m "Bump version to %s"
                  echo "::set-output name=new_version::$(node -p "require('./package.json').version")"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  branch: master

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.bump_version.outputs.new_version }}
                  release_name: Release ${{ steps.bump_version.outputs.new_version }}
                  body: |
                      Describe your changes here

            - name: Check npm token
              run: echo $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
