name: Release and Publish to npm

on:
    push:
        tags:
            - 'v*.*.*' # Запуск при пуше тегов, соответствующих шаблону

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # Ensure the entire history is fetched so that we can push tags
                  persist-credentials: false # Не сохранять учетные данные

            - name: Set up Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Check for existing tag
              id: check_tag
              run: |
                  TAG_EXISTS=$(git tag -l "v$(node -p "require('./package.json').version")")
                  echo "::set-output name=tag_exists::$TAG_EXISTS"

            - name: Delete existing tag
              if: steps.check_tag.outputs.tag_exists
              run: |
                  git tag -d "v$(node -p "require('./package.json').version")"
                  git push origin :refs/tags/v$(node -p "require('./package.json').version")
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Bump version
              id: bump_version
              run: |
                  CURRENT_VERSION=$(node -p "require('./package.json').version")
                  NEW_VERSION=$(npm version patch -m "Bump version to %s")
                  echo "::set-output name=new_version::$NEW_VERSION"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Push changes
              run: |
                  git push origin HEAD --tags
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ steps.bump_version.outputs.new_version }}
                  release_name: Release ${{ steps.bump_version.outputs.new_version }}
                  body: |
                      ## Changes
                      - Describe your changes here

            - name: Check npm token
              run: echo $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
